### PR TITLE
Add Hero Image Preloader

### PR DESCRIPTION
**Pull request by HardeepAsrani**
### All Submissions:

* [x] Have you followed the [Optimole Contributing guideline](https://github.com/Codeinwp/optimole-wp/blob/master/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change? 
 

### Changes proposed in this Pull Request:
 
This tries to detect Hero Images and adds `fetchpriority="high"` to them. It looks for the first image that matches the description and doesn't add it to any other images.

It also adds it to the first Site Logo if the theme is using WordPress' core logo function. Apart from that, for Hero Images it looks for:

- Page Header, if called using WP Core functions.
- Post Thumbnail, if called and used using WP Core functions.
- Image: If called using wp_get_attachment_image + it is the thumbnail of the post.
- Image in Post Content: If nothing is fount until the content, it uses the `wp_content_img_tag` to find the first image of the post and adds it to it. This also works with FSE themes.

I ran some tests with Neve & Neve FSE and here how the comparisons look, I'd recommend that we also try to test out a larger sample using maybe demosites staging.

Screenshot 2023-07-03 at 9 20 24 PM
Screenshot 2023-07-03 at 9 20 31 PM

Closes https://github.com/Codeinwp/optimole-service/issues/763.

### How to test the changes in this Pull Request:

1. Using https://www.webpagetest.org/webvitals, do test same websites with and without this version of the plugin. To prevent caching from meddling, better to have two websites with same data.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by GrigoreMihai — APPROVED** [review]

**Review by abaicus — APPROVED** [review]

**Comment by irinelenache** [comment]
@HardeepAsrani Tested the PR and didn't get some consistent results, sometimes the metrics are better without the preloader. I tested on https://gtmetrix.com/ , https://www.webpagetest.org/ and Chrome Lighthouse.
I used two identical wordpress intances and some starter sites (preload1 **is not** using preloader and preload2 **is using** it)
- Music band demosite, using Gtmetrix - [homepage](https://vertis.d.pr/i/m24Q7x), [album page](https://vertis.d.pr/i/VRrlfq)
- Job board demosite, using Webpagetest - [homepage without PR](https://vertis.d.pr/i/LNOs1Y) / [homepage with PR](https://vertis.d.pr/i/HjIBWH), [about us page without PR](https://vertis.d.pr/i/rpn9hE) / [about us page with PR](https://vertis.d.pr/i/zUsFkR), 
- Job board demosite, using Chrome Lighthouse - [homepage without PR](https://vertis.d.pr/i/HJlfiI) / [homepage with PR](https://vertis.d.pr/i/eYx2VM), [about us page without PR](https://vertis.d.pr/i/3mSOVv) / [about us page with PR](https://vertis.d.pr/i/Jvti8b)

Login details for both websites:
```
https://preload1.vertisite.cloud/wp-admin
User: giduluviku5056
Password: oiOVwj1ef5MsWJp8L0Rg

https://preload2.vertisite.cloud/wp-admin
User: fafezaguci8989
Password: eF0zcqEkUNv4xMt3lYwA
```

Let me know if this happens for you also or i misunderstood anything 🙏

**Comment by HardeepAsrani** [comment]
@irinelenache Would it be possible for you to test it with two identical sites hosted on same platform as to avoid cache? One with the Pr applied, one without?

**Comment by irinelenache** [comment]
> @irinelenache Would it be possible for you to test it with two identical sites hosted on same platform as to avoid cache? One with the Pr applied, one without?

@HardeepAsrani Isn't that the method i used? (2 identical InstaWP sites)

**Comment by HardeepAsrani** [comment]
@abaicus As talked about it during the L10, I ran more tests and same results, sometimes one being faster than the other but mostly on new instance in first test, the one with applied PR being faster. 😄

**Comment by abaicus** [comment]
@HardeepAsrani what is the status here? Is there anything more you want to add to this PR?

**Comment by HardeepAsrani** [comment]
@abaicus All done in part of coding. In terms of testing, not sure how to test given the results are always inconsistent?

**Comment by abaicus** [comment]
@HardeepAsrani, from my point of view, as long as the fetch priority of the request is correct and the attribute is added to the DOM, things work fine.

**Comment by HardeepAsrani** [comment]
@abaicus If that's the case, then it's good to go.

**Pull request merged**
