### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by GrigoreMihai**
Fixes https://github.com/Codeinwp/optimole-service/issues/618 , https://github.com/Codeinwp/optimole-service/issues/617 , https://github.com/Codeinwp/optimole-service/issues/616 .

### CODE REVIEW

**Comment by irinelenache** [comment]
@GrigoreMihai The issues linked to the PR are fixed 🚀 

I have a single mention, should we add the external link icon to the links in the plugin, like [we do in Neve](https://vertis.d.pr/i/Su2B38) for example?

**Comment by GrigoreMihai** [comment]
> @GrigoreMihai The issues linked to the PR are fixed 🚀
> 
> I have a single mention, should we add the external link icon to the links in the plugin, like [we do in Neve](https://vertis.d.pr/i/Su2B38) for example?

Nice suggestion, I added them for the cloud library docs, let me know if they look ok on your end. @irinelenache

**Comment by irinelenache** [comment]
@GrigoreMihai 

- [ ] For this [yellow notice](https://vertis.d.pr/i/m8HAuS), the pointer is still active even if it's not clickable 
- [ ] The icon in the cloud library doc link appears on the next line for me (using 14inch macbook) https://vertis.d.pr/i/vRDDFH
- [ ] Maybe we can add the icon to [these links](https://vertis.d.pr/i/lxY0LJ) also, they all are external links

**Comment by GrigoreMihai** [comment]
@irinelenache , fixed them now, let me know how they look.

**Comment by irinelenache** [comment]
@GrigoreMihai All issues are fixed now, thank you 🚀

**Pull request merged**
