### PR TITLE
Fix Images with a Bullet symbol not being optimized

### PR DESCRIPTION
**Pull request by HardeepAsrani**
### All Submissions:

* [x] Have you followed the [Optimole Contributing guideline](https://github.com/Codeinwp/optimole-wp/blob/master/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change? 
 

### Changes proposed in this Pull Request:
 
Previously, images with UTF character 2022, ie the bullet, weren't being optimized. The fix makes sure they are working properly.

Closes https://github.com/Codeinwp/optimole-service/issues/738

### How to test the changes in this Pull Request:

1. Upload an image with the bullet character in its filename, for example `DSCF4559-Edité-•-©-Josef-Helie.png`
2. Add it to your post, and confirm the Optimole CDN URL is being applied to it.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by selul** [comment]
@HardeepAsrani can you add also an unit test, it's pretty straighforward to add one.

**Review by GrigoreMihai — APPROVED** [review]
LGTM, one small thing I would do is to also add an URL for this case for the default replacement here: https://github.com/Codeinwp/optimole-wp/blob/master/tests/test-replacer.php#L310 .

**Comment by HardeepAsrani** [comment]
@GrigoreMihai Done.

**Comment by rodica-andronache** [comment]
@HardeepAsrani hi! just wanted to make sure, this is supposed to fix the issue just with the bullet symbol ( which is does ).
Saw that for some other symbols, for e.g. `^` Optimole does not optimize the image (the final image here https://rodicaelena.com/moments/). Is that something I should create another issue for?

**Comment by HardeepAsrani** [comment]
@GrigoreMihai Is there any reason why we don't just accept all the keyboard symbols with a wildcard? Could it cause any issues?

**Comment by HardeepAsrani** [comment]
Thanks @GrigoreMihai, I've only added `^` caret support, seems like most of the keyboard characters are stripped out of the URL when you upload the image, so we don't need to support. Let me know if anything else is needed here.

**Pull request merged**
