### PR TITLE
Fix error when auto-connecting with option

### PR DESCRIPTION
**Pull request by HardeepAsrani**
### All Submissions:

* [x] Have you followed the [Optimole Contributing guideline](https://github.com/Codeinwp/optimole-wp/blob/master/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change? 
 

### Changes proposed in this Pull Request:

If you use auto_connect using options and the option keeps there (in my usecase I had kept update_option run on init) then the auto_connect goes on and ends with an error if the account with that email already exists in console but the UI shows nothing, so one can't change the email or anything to connect. 

Closes https://github.com/Codeinwp/optimole-service/issues/678.

### How to test the changes in this Pull Request:

1. Use update_option to set the email on init.
2. If the email gets registered for the first time, disconnect and refresh the page.
3. The page will load to connect and then show nothing.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by GrigoreMihai — APPROVED** [review]

**Comment by irinelenache** [comment]
@HardeepAsrani @GrigoreMihai Can you provide some more testing steps for this? I didn't exactly understand how to test this PR 🙏

**Comment by HardeepAsrani** [comment]
@irinelenache When you test, you can put the following code somewhere in WordPress, let's functions.php file of the theme or optimole-test plugin if you have it:

```
add_action( 'init', function() {
    update_option( 'optml_user_email', 'youremail@gmail.com' );
} );
```

If you use an email that is already used with Optimole, you will see how before this PR the Optimole screen loads and shows nothing, and after this PR it shows an error.

If you are unsure about which email to use, just use whatever you want and disconnect after the initial connection. Let me know if that helps.

**Comment by irinelenache** [comment]
@HardeepAsrani I followed your instructions and i don't see any error, the Optimole screen still shows nothing for me

You can check here, i used irinel@themeisle.com for connecting to Optimole
```
 Admin area URL: https://older-mole.s4-tastewp.com/wp-admin 
 Username: irinel 
 Password: qCDBrxMJEG0 
```

**Comment by HardeepAsrani** [comment]
Thanks @irinelenache, I see that when I do this same I get a different error message on my local instance versus when I do it on tastewp.com, I've updated the PR to make sure it bails out of auto-connect regardless of the error.

**Comment by HardeepAsrani** [comment]
@irinelenache It should work fine now, I updated the plugin on your test instance. I had to flush the browser cache by bumping up the version. You can test now.

**Comment by irinelenache** [comment]
@HardeepAsrani It works fine now, thank you 🚀

**Pull request merged**
