### PR TITLE
Feat/edit import

### PR DESCRIPTION
**Pull request by abaicus**
### All Submissions:

* [x] Have you followed the [Optimole Contributing guideline](https://github.com/Codeinwp/optimole-wp/blob/master/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change? 
 

### Changes proposed in this Pull Request:
- Adds compatibility for importing DAM-edited images;
- Ensures that edits are imported and that duplicate checks get skipped for them, allowing multiple imports;
- Fixes issue where we returned `true` from the `get_attached_file` method - this showed up in the attachment edit page, and the media library list view in the dashboard as `1` under **File name**, because `true` was treated as a string:
 
<details>
<summary>Before</summary>

image
image

</details>
<details>
<summary>Now</summary>

image
image

</details>

Closes Codeinwp/optimole-service#649.

#### Prerequisites: 
- Needs https://github.com/Codeinwp/optimole-service/pull/1055 to be merged;
- Needs https://github.com/Codeinwp/optimole-lambda-functions/pull/464 to be merged;

#### Checking the import:
1. Create a post, and open the Optimole DAM importer in the media modal;
2. Right-click any image, or open the top-right menu for it and click edit;
3. This should allow you to edit the image and insert it into the content using the `Insert Image` button in the modal;
4. For edits this is the only way of inserting them for now;
5. Images should work as expected, including:
  - image sizes;
  - images imported as backgrounds;
  - images used in Elementor;
6. Different edits for the same image should be imported each time you edit it;

#### What to check in the URLs:
- Backend:
  - I would advise using the **Copy url** button in the WordPress dashboard media library to check if these parameters apply after importing edited images;
  - If the image is not resized from the edit modal, there should be no `c:<width>:<height>:<gravity>`, or `rt:fill` parameter;
  - If the image is resized either in width or height, or both, they should both appear;

- On frontend:
  - This should still be compatible with lazy-loading, and all the image parameters added by the plugin. You can refer to this PR: https://github.com/Codeinwp/optimole-wp/pull/653
  - Similar to what I mentioned above in the last two points, it should happen on fronted links as well;

**I hope this information proves useful. Please do not hesitate to contact me if you need any clarifications regarding how this works. 🙏🏻  Thank you!**

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by GrigoreMihai — APPROVED** [review]

**Comment by irinelenache** [comment]
@abaicus Solid work 🚀 Tested and found a few things:

- [ ] When i'm inserting an image as a section background and i'm changing the width/height in the edit image modal, the inserted image won't look like the one in the modal. Here is a video with the behaviour https://vertis.d.pr/v/GqCCRz
- [ ] If i open the edit image modal, make some changes there, close it and open it again, the changes won't be saved. Starting with the second edit, the changes will be there https://vertis.d.pr/v/d5LLQZ
- [ ] Is it expected that now you can edit .gif files? Previously you could only change settings without having any effect
- [ ] If i'm opening the edit image page for an image that was edited and imported using Optimole, there will be some warning there https://vertis.d.pr/i/9Kab6M (I don't know if this is because i offloaded the images. I tried rollbacking but it isn't working, probably because of the staging capabilities) 

You can check the issues here
```
URL: https://ss-skylark-kama.vertisite.cloud
Username: dazavekara1225
Password: Q95Zr8YxjPpnvOXafGAk
```

**Comment by abaicus** [comment]
@irinelenache Things should be okay now. I tested on the provided instance, and this fix should circumvent the warning when the open_basedir restriction is in effect. 👍🏻  

I think that the edited/dam attachments weren't loading previously in the core media-modal library tab before as well on the provided instance. 

Let me know if you find anything else! Thanks! 🚀

**Comment by AndreeaCristinaRadacina** [comment]
Hi there,

I am not sure if we can do something about this, but when I use a smaller window, the modal turns blank, and it won't work anymore unless I close it and open it again:
image

**Comment by abaicus** [comment]
@AndreeaCristinaRadacina Can you provide some reproduction steps for this?

**Comment by AndreeaCristinaRadacina** [comment]
Sure. It occurs when you try to replace an image. I recorded a loom video for this - https://www.loom.com/share/946d5b436dc04348a0b85aff8554e081?sid=5352e8ef-2fd4-4ec6-b70e-ad14f28f79ed

**Comment by abaicus** [comment]
@AndreeaCristinaRadacina This occurs even if all plugins are deactivated, so it seems to be a WP core issue. There's not much we can do about it.

**Comment by AndreeaCristinaRadacina** [comment]
@abaicus, thank you for checking!

**Comment by irinelenache** [comment]
@abaicus The mentioned issue is fixed now, thank you 🚀 No other issues found regarding the edit import ✔️ 
Found something else:

- [ ] After offloading and then rollbacking all the images, most of them have 150/150px in frontend https://vertis.d.pr/i/A2AVf9 https://vertis.d.pr/i/X4g2Xk

You can check here:
```
URL : https://ange-skunk-huva.vertisite.cloud
Username : ririyimobu3008
Password : 75I8dZzFBrJqjMARKuTO
```

**Comment by abaicus** [comment]
@irinelenache as mentioned on slack. This seems to be an issue with the respective demosite. The images are actually set as `thumbnail` in the content. It's also unrelated to this PR as I've tested with the production version, and the same thing seems to happen on another instance: https://nvious-eel-xota.instawp.xyz 


### Demosites.io backend screenshots:
image
image

**Comment by irinelenache** [comment]
@abaicus Thank you for looking into it ✅ 

I'll move this to **Ready to merge** as there are no other problems and we'll have another look while testing the release builds 🚀

**Pull request merged**
