### PR TITLE
feat: add frontend banner mechanism [ref: Codeinwp/optimole-service#100]

### PR DESCRIPTION
**Pull request by abaicus**
### All Submissions:

* [x] Have you followed the [Optimole Contributing guideline](https://github.com/Codeinwp/optimole-wp/blob/master/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change? 
 

### Changes proposed in this Pull Request:
- Adds setting to enable frontend banner under **Settings > General;**
- This setting is synced across all user websites;

<details>
<summary>Dashboard screenshot</summary>

image

</details>
 

Closes Codeinwp/optimole-service#100.

### Steps

1. Install the plugin on a website;
2. The new setting should be available in the dashboard (by default, it's disabled);
3. When you enable it and save the settings, a banner should appear on the front end;
4. The sync happens when the daily_sync is run, or when you connect a new website using the same API key;
5. For websites that have been previously connected, we have a 5-minute cache, so that time should have passed when you are reconnecting an existing website to test that the setting is synced;
6. The setting should be kept in sync by the refresh stats button in the top-right dropdown as well - provided the cache time has passed;
7. In all other cases, the sync will happen only when the daily sync is ran;

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by GrigoreMihai — APPROVED** [review]
LGTM, just a small thing that might help the testing, the daily sync can also be triggered from here: https://vertis.d.pr/i/YzXiho it is the same as `wp cron event run optml_daily_sync`

**Comment by abaicus** [comment]
Thanks for the pointer, @GrigoreMihai! 🚀  I've updated the testing instructions as well 👍🏻

**Comment by abaicus** [comment]
@GrigoreMihai, I made some changes here. Due to the cache, we have on the dashboard end (5 minutes for each site), if you jump from one dashboard to another after changing the setting, I also updated the `extra_visits` on the dashboard with the cached version, which shouldn't have happened.

**Comment by GrigoreMihai** [comment]
@abaicus Not sure right now when we will update the dashboard with the setting from the plugin since the update function is no longer called when changing the setting which means this is also not called: https://github.com/Codeinwp/optimole-wp/pull/554/files#diff-d1fc3e16afc6476c7f6323a308fbc467625e9ba3413d990c5a58414eefa3d204R427 ?

**Review by GrigoreMihai — APPROVED** [review]
@abaicus Thanks for the details missed that, sorry about it. Everything is good to go.

**Comment by abaicus** [comment]
@GrigoreMihai No problem, don't worry! Thanks for checking it out! 🚀

**Comment by irinelenache** [comment]
@abaicus Tested and everything works fine now 🚀 I guess we should also inform the users in the documentation about the 5 minutes delay for the sync to happen 📝  cc @AndreeaCristinaRadacina

**Comment by abaicus** [comment]
Thank you, @irinelenache! 🚀

**Pull request merged**
