### PR TITLE
fix: sites not being removed from cloud library whitelist

### LINKED ISSUE #588: Site selection for cloud browsing not working
### Description

Cloud browsing site selection doesn't work properly since we translated to react. You can't remove sites if you have more than one selected.

It seems that the value is not structured correctly, and the sanitization breaks it because of the `array_replace_recursive` here: https://github.com/codeinwp/optimole-wp/blob/5b05defe2a3c7d8e6c37e281fad5c408c3d91507/inc/settings.php#L276

### Step-by-step reproduction instructions

- Have more than one site connected to the account;
- Turn on cloud browsing;
- Select all sites in the dropdown and save;
- Reload the page;
- Remove one of the sites and save;
- Refresh the page;
- The control wasn't changed;

### Screenshots, screen recording, code snippet or Help Scout ticket

image

### Environment info

_No response_

### Is the issue you are reporting a regression

Yes, this is a regression.

### PR DESCRIPTION
**Pull request by HardeepAsrani**
### All Submissions:

* [x] Have you followed the [Optimole Contributing guideline](https://github.com/Codeinwp/optimole-wp/blob/master/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change? 
 

### Changes proposed in this Pull Request:
Fixes the issue with domains not being removed from cloud library whitelist. 
 

Closes #588.

### How to test the changes in this Pull Request:

1. Connect a website with multiple domains with images.
2. Enable the library and see if images from all sites are being fetched. Confirm this doesn't happen: https://github.com/Codeinwp/optimole-wp/issues/588
3. Whitelist multiple domains and confirm images are only loading from those sites.
4. Remove some of those domains and confirm images are only loading from whitelisted sites.
5. Remove all the domains and confirm images are being loaded from all the domains.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by abaicus — APPROVED** [review]

**Comment by rodica-andronache** [comment]
@HardeepAsrani the issue from [here](https://github.com/Codeinwp/optimole-wp/issues/588) is fixed, but:

I have two instances, each one with just one image 
`https://rhinoceros-rara.vertisite.cloud/wp-admin/
user: admin
pass: PpdN*j1p!Da2Pb1zkT7L4B0)
`
`https://l-squirrel-mole.vertisite.cloud/wp-admin/
user: admin
pass: QftWVbIGU56r0U1usjQg%x$j`

If I enable cloud library browsing, and go to create a new post, and add an image from Optimole, the images seems to be broken in my case https://vertis.d.pr/v/4HROOS
Is there's something I'm missing? Thank you!

**Comment by abaicus** [comment]
@rodica-andronache, it seems that the images are getting pulled from the `production` CDN instead of the staging inside the instances you mentioned, while they should be pulled from production, i.e.

``` diff
- https://mlvrbpl8hd9a.i.optimole.com/w:150/h:150/q:mauto/rt:fill/g:ce/proces…ps://rhinoceros-rara.vertisite.cloud/wp-content/uploads/2023/07/puppy.jpeg 404
// instead of 
+ https://mlvrbpl8hd9a.b.optml.cloud/w:150/h:150/q:mauto/rt:fill/g:ce/proces…ps://rhinoceros-rara.vertisite.cloud/wp-content/uploads/2023/07/puppy.jpeg 404
```

I don't think this is related to the current issue, but we can further investigate on a different issue.

**Comment by abaicus** [comment]
@HardeepAsrani this probably happens due to the fact that the dev build accounts for `WP_INC`, while the query is an ajax action:

https://github.com/codeinwp/optimole-wp/blob/46b8a7b5962a4a919e7a875159db61c247ef4e9a/development.php#L8-L10

I think we can safely remove that check in the development build file.

**Comment by HardeepAsrani** [comment]
Good catch @abaicus, I've removed it.

**Comment by abaicus** [comment]
@HardeepAsrani I tried this on two different instances (using the build zip file with the old constants), and even if the image display is working fine, it seems like the exclusion isn't happening. 

- Activate cloud browsing & add just one of the sites to the filter;
- Create a new post > add an image block > open the media modal and switch to the optimole tab;
- All the images are there, even though they should be excluded;

Here are the website details:

https://y-ladybird-wovu.instawp.xyz/
U : `lipecilebu7209`
P : `ktRwin7N2HWmrY4hQa30`
---
https://ul-polecat-yuki.instawp.xyz/wp-admin
U: `gibexonize9371`
P: `qBoDcjVgeuzKw9siN7dR`

**Comment by HardeepAsrani** [comment]
Should be fixed now.

**Comment by rodica-andronache** [comment]
@HardeepAsrani it's working well now, thank you!
With the dev build, I have the same issue as here https://github.com/Codeinwp/optimole-wp/pull/589#issuecomment-1621434689 but @abaicus is having a look 🚀

**Comment by abaicus** [comment]
I have fixed the dev build issue here: https://github.com/Codeinwp/optimole-wp/pull/593

Thank you for all the help 🚀

**Pull request merged**
